# CMake generated Testfile for 
# Source directory: /home/guangping/dev/cpp/GIT/QGIS/tests/src/gui
# Build directory: /home/guangping/dev/cpp/GIT/QGIS/tests/src/gui
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(qgis_zoomtest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_zoomtest")
add_test(qgis_edittooltest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_edittooltest")
add_test(qgis_categorizedrendererwidget "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_categorizedrendererwidget")
add_test(qgis_datumtransformdialog "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_datumtransformdialog")
add_test(qgis_doublespinbox "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_doublespinbox")
add_test(qgis_dualviewtest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_dualviewtest")
add_test(qgis_attributeformtest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_attributeformtest")
add_test(qgis_dockwidget "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_dockwidget")
add_test(qgis_fieldexpressionwidget "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_fieldexpressionwidget")
add_test(qgis_filewidget "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_filewidget")
add_test(qgis_focuswatcher "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_focuswatcher")
add_test(qgis_mapcanvastest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_mapcanvastest")
add_test(qgis_messagebartest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_messagebartest")
add_test(qgis_projectionissues "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_projectionissues")
add_test(qgis_qgsguitest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_qgsguitest")
add_test(qgis_processingguitest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_processingguitest")
add_test(qgis_processingmodeltest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_processingmodeltest")
add_test(qgis_rubberbandtest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_rubberbandtest")
add_test(qgis_scalecombobox "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_scalecombobox")
add_test(qgis_scalerangewidget "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_scalerangewidget")
add_test(qgis_rangewidgetwrapper "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_rangewidgetwrapper")
add_test(qgis_spinbox "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_spinbox")
add_test(qgis_sqlcomposerdialog "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_sqlcomposerdialog")
add_test(qgis_editorwidgetregistrytest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_editorwidgetregistrytest")
add_test(qgis_keyvaluewidgettest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_keyvaluewidgettest")
add_test(qgis_listwidgettest "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_listwidgettest")
add_test(qgis_filedownloader "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_filedownloader")
add_test(qgis_layoutgui "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_layoutgui")
add_test(qgis_layoutview "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_layoutview")
add_test(qgis_valuemapwidgetwrapper "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_valuemapwidgetwrapper")
add_test(qgis_valuerelationwidgetwrapper "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_valuerelationwidgetwrapper")
add_test(qgis_relationreferencewidget "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_relationreferencewidget")
add_test(qgis_featurelistcombobox "/home/guangping/dev/cpp/GIT/QGIS/tests/src/gui/../../../output/bin/qgis_featurelistcombobox")
