# Install script for directory: /home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/qgis/python/plugins/processing/algs/grass7" TYPE FILE FILES
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/Grass7Algorithm.py"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/Grass7AlgorithmProvider.py"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/Grass7Utils.py"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/__init__.py"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/grass7.txt"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/qgis/python/plugins/processing/algs/grass7/description" TYPE FILE FILES
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.albedo.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.aster.toar.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.atcorr.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.biomass.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.cca.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.cluster.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.colors.enhance.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.eb.eta.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.eb.evapfr.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.eb.hsebal01.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.eb.netrad.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.eb.soilheatflux.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.emissivity.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.evapo.mh.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.evapo.pm.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.evapo.pt.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.evapo.time.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.fft.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.gensig.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.gensigset.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.group.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.his.rgb.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.ifft.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.image.mosaic.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.in.spotvgt.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.landsat.acca.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.landsat.toar.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.maxlik.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.modis.qc.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.oif.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.pansharpen.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.pca.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.rgb.his.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.segment.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.smap.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.tasscap.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.topo.corr.ill.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.topo.corr.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.vi.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/i.zc.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/m.cogo.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/nviz.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.basins.fill.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.blend.combine.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.blend.rgb.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.buffer.lowmem.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.buffer.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.carve.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.category.out.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.category.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.circle.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.clump.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.coin.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.colors.out.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.colors.stddev.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.colors.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.composite.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.contour.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.cost.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.covar.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.cross.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.describe.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.distance.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.drain.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.fill.dir.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.fill.stats.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.fillnulls.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.flow.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.geomorphon.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.grow.distance.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.grow.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.gwflow.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.his.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.horizon.height.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.horizon.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.in.lidar.info.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.in.lidar.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.info.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.kappa.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.lake.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.latlong.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.cwed.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.cwed.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.dominance.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.dominance.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.edgedensity.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.edgedensity.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.mpa.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.mpa.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.mps.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.mps.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.padcv.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.padcv.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.padrange.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.padrange.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.padsd.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.padsd.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.patchdensity.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.patchdensity.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.patchnum.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.patchnum.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.pielou.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.pielou.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.renyi.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.renyi.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.richness.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.richness.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.shannon.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.shannon.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.shape.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.shape.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.simpson.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.li.simpson.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.mapcalc.simple.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.mask.rast.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.mask.vect.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.mfilter.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.mode.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.neighbors.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.null.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.gridatb.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.mat.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.mpeg.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.png.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.pov.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.ppm.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.ppm3.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.vrml.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.vtk.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.out.xyz.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.param.scale.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.patch.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.plane.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.profile.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.proj.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.quant.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.quantile.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.random.cells.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.random.surface.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.random.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.reclass.area.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.reclass.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.recode.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.regression.line.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.regression.multi.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.relief.scaling.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.relief.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.report.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.resamp.bspline.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.resamp.filter.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.resamp.interp.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.resamp.rst.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.resamp.stats.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.resample.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.rescale.eq.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.rescale.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.rgb.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.ros.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.series.accumulate.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.series.interp.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.series.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.shade.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.sim.sediment.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.sim.water.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.slope.aspect.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.solute.transport.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.spread.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.spreadpath.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.statistics.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.stats.quantile.out.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.stats.quantile.rast.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.stats.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.stats.zonal.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.stream.extract.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.sun.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.sunhours.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.sunmask.datetime.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.sunmask.position.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.surf.area.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.surf.contour.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.surf.fractal.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.surf.gauss.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.surf.idw.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.surf.random.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.terraflow.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.texture.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.thin.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.tile.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.tileset.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.to.vect.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.topidx.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.topmodel.topidxstats.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.topmodel.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.transect.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.univar.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.uslek.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.usler.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.viewshed.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.volume.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.walk.coords.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.walk.points.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.walk.rast.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.water.outlet.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.watershed.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.what.color.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.what.coords.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/r.what.points.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.buffer.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.build.check.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.build.polylines.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.class.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.clean.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.cluster.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.db.select.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.decimate.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.delaunay.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.dissolve.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.distance.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.drape.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.edit.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.extract.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.extrude.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.generalize.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.hull.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.dxf.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.e00.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.geonames.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.lidar.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.lines.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.mapgen.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.in.wfs.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.info.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.kcv.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.kernel.rast.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.kernel.vect.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.lidar.correction.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.lidar.edgedetection.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.lidar.growing.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.mkgrid.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.neighbors.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.alloc.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.allpairs.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.bridge.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.centrality.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.components.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.connectivity.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.distance.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.flow.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.iso.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.nreport.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.path.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.report.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.salesman.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.spanningtree.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.steiner.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.timetable.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.net.visibility.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.normal.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.out.ascii.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.out.dxf.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.out.postgis.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.out.pov.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.out.svg.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.out.vtk.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.outlier.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.overlay.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.pack.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.parallel.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.patch.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.perturb.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.proj.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.qcount.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.random.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.rast.stats.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.reclass.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.rectify.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.report.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.sample.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.segment.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.select.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.split.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.surf.bspline.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.surf.idw.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.surf.rst.cvdev.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.surf.rst.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.to.3d.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.to.lines.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.to.points.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.to.rast.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.transform.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.type.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.univar.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.vect.stats.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.voronoi.skeleton.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.voronoi.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.what.rast.txt"
    "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/description/v.what.vect.txt"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/guangping/dev/cpp/GIT/QGIS/python/plugins/processing/algs/grass7/ext/cmake_install.cmake")

endif()

