FILE(MAKE_DIRECTORY "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/.")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/__init__.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/.")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/link_types.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/.")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/plugin.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/.")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/util.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/.")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/metadata.txt" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/.")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/LICENSE.txt" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/.")
FILE(MAKE_DIRECTORY "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/ui")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/ui/maindialog.ui" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/ui")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/ui/manageconnectionsdialog.ui" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/ui")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/ui/newconnectiondialog.ui" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/ui")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/ui/recorddialog.ui" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/ui")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/ui/xmldialog.ui" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/ui")
FILE(MAKE_DIRECTORY "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/dialogs")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/dialogs/__init__.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/dialogs")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/dialogs/maindialog.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/dialogs")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/dialogs/manageconnectionsdialog.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/dialogs")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/dialogs/newconnectiondialog.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/dialogs")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/dialogs/recorddialog.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/dialogs")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/dialogs/xmldialog.py" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/dialogs")
FILE(MAKE_DIRECTORY "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/images")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/images/MetaSearch.svg" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/images")
FILE(MAKE_DIRECTORY "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/resources")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/resources/connections-default.xml" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/resources")
FILE(MAKE_DIRECTORY "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/resources/templates")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/resources/templates/record_metadata_dc.html" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/resources/templates")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/resources/templates/service_metadata.html" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/resources/templates")
FILE(COPY "/home/guangping/dev/cpp/GIT/QGIS/python/plugins/MetaSearch/resources/templates/xml_highlight.html" DESTINATION "/home/guangping/dev/cpp/GIT/QGIS/output/python/plugins/MetaSearch/resources/templates")
